[project]
name = "metldata"
version = "4.0.4"
description = "metldata - A framework for handling metadata based on ETL, CQRS, and event sourcing."
dependencies = [
    "hexkit[akafka,mongodb] >=7.1, <8",
    "ghga-service-commons[api,auth] >=6.0.0, <7",
    "ghga-event-schemas >=9.2.0, <10",
    "typer >= 0.19",
    "linkml == 1.6.1",
    "linkml-runtime == 1.6.0",
    "linkml-validator == 0.4.5",
    "cryptography >= 45.0.3",
    "pydantic >= 2.12.0"
]

[project.urls]
Repository = "https://github.com/ghga-de/metldata"

[project.scripts]
metldata = "metldata.__main__:run"
